### ISSUE TITLE
Monapt breaking changes in 0.7.0

### ISSUE THREAD

**Issue by jklmli** [AKIRA-MIYAKE/lamprox#2]
Hi, I'm the author of [monapt](http://github.com/jiaweihli/monapt).

I saw on npm that you're using monapt.  Thanks!
I just released a new version, [0.7.0](https://github.com/jiaweihli/monapt/releases/tag/0.7.0).  It has breaking changes that will affect your codebase.  But hopefully it will make your code easier 😄 

Feel free to close this issue whenever!

**Comment by AKIRA-MIYAKE** [comment]
Thank you for letting me know the update!!
I will check it and respond if necessary.

**Comment by AKIRA-MIYAKE** [comment]
Done in #3
